JFLAGS = 
JC = javac
.SUFFIXES: .java .class
.java.class:
	$(JC) $(JFLAGS) $*.java
	
CLASSES = \
	NeuralNode.java \
	NeuralNetwork.java \
	Main.java
	
default: classes

classes: $(CLASSES:.java=.class)

clean:
	$(RM) *.class